<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "momo_preciousmetal"
 *
 * Auto generated by Extension Builder 2019-12-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Precious metal',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Masod Mohmand',
    'author_email' => 'masod@momo-webdevelopment.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.4',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
